version: 2.1

jobs:
  build-and-push:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - run:
          name: Install QEMU for Multi-Arch Support
          command: docker run --privileged --rm tonistiigi/binfmt --install all

      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Create Buildx Builder
          command: docker buildx create --name mybuilder --use

      - run:
          name: Build and Push API Image (ARM64)
          command: |
            docker buildx build \
              --platform linux/arm64 \
              -t yehonatancohen/whatsapp-crm-backend:latest \
              --push .

      - run:
          name: Build and Push Nginx Image (ARM64)
          command: |
            docker buildx build \
              --platform linux/arm64 \
              -t yehonatancohen/whatsapp-crm-nginx:latest \
              --push ./nginx

workflows:
  build_pipeline:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
