// Known disposable/temporary email domains
const DISPOSABLE_DOMAINS: Set<string> = new Set([
  // Major disposable services
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.info', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamailblock.com', 'tempmail.com', 'temp-mail.org',
  'temp-mail.io', 'throwaway.email', 'yopmail.com', 'yopmail.fr',
  '10minutemail.com', '10minutemail.net', 'trashmail.com', 'trashmail.net',
  'sharklasers.com', 'grr.la', 'pokemail.net', 'spam4.me',
  // More disposable domains
  'binkmail.com', 'bobmail.info', 'chammy.info', 'devnullmail.com',
  'letthemeatspam.com', 'maildrop.cc', 'mailnesia.com', 'mailsac.com',
  'mintemail.com', 'mt2015.com', 'nada.email', 'spamfree24.org',
  'tempr.email', 'discard.email', 'dispostable.com', 'fake-box.com',
  'getairmail.com', 'harakirimail.com', 'mailcatch.com', 'mailexpire.com',
  'mailforspam.com', 'mohmal.com', 'mytemp.email', 'throwam.com',
  'trashemail.de', 'wegwerfmail.de', 'wegwerfmail.net', 'einrot.com',
  'fakeinbox.com', 'fastacura.com', 'filzmail.com', 'flitmail.com',
  'gishpuppy.com', 'grandmamail.com', 'haltospam.com', 'jetable.org',
  'kasmail.com', 'koszmail.pl', 'kurzepost.de', 'lhsdv.com',
  'mailblocks.com', 'mailbox52.ga', 'mailbox80.biz', 'mailbox92.biz',
  'mailcatch.com', 'mailchop.com', 'maildu.de', 'maileater.com',
  'mailfreeonline.com', 'mailguard.me', 'mailimate.com', 'mailin8r.com',
  'mailinator.net', 'mailinator2.com', 'mailincubator.com', 'mailismagic.com',
  'mailme.ir', 'mailme.lv', 'mailmetrash.com', 'mailmoat.com',
  'mailnull.com', 'mailshell.com', 'mailsiphon.com', 'mailslite.com',
  'mailtemp.info', 'mailtothis.com', 'mailzilla.com', 'meltmail.com',
  'messagebeamer.de', 'mezimages.net', 'mfsa.ru', 'mycleaninbox.net',
  'mytrashmail.com', 'nervmich.net', 'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'notmailinator.com', 'nowmymail.com', 'nurfuerspam.de', 'nus.edu.sg',
  'oneoffemail.com', 'onewaymail.com', 'otherinbox.com', 'owlpic.com',
  'pjjkp.com', 'plexolan.de', 'pookmail.com', 'proxymail.eu',
  'rcpt.at', 'reallymymail.com', 'recode.me', 'regbypass.com',
  'rhyta.com', 'rklips.com', 'rmqkr.net', 'royal.net',
  'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net',
  'safersignup.de', 'safetymail.info', 'sandelf.de', 'saynotospams.com',
  'scatmail.com', 'schafmail.de', 'selfdestructingmail.com', 'sendspamhere.com',
  'shiftmail.com', 'shirleywe.com', 'skeefmail.com', 'slaskpost.se',
  'slipry.net', 'slopsbox.com', 'smashmail.de', 'soodonims.com',
  'spam.la', 'spamavert.com', 'spambob.com', 'spambob.net',
  'spambob.org', 'spambox.us', 'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com', 'spamex.com',
  'spamfighter.cf', 'spamfighter.ga', 'spamfighter.gq', 'spamfighter.ml',
  'spamfighter.tk', 'spamfree.eu', 'spamgoes.in', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com',
  'spamhole.com', 'spamify.com', 'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de', 'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamslicer.com', 'spamspot.com', 'spamstack.net',
  'spamtrail.com', 'spamtrap.ro', 'superrito.com', 'suremail.info',
  'teleworm.us', 'tempail.com', 'tempalias.com', 'tempe4mail.com',
  'tempemail.co.za', 'tempemail.net', 'tempinbox.com', 'tempinbox.co.uk',
  'tempmail.eu', 'tempmail.it', 'tempmaildemo.com', 'tempmailer.com',
  'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br', 'temporaryemail.net',
  'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
  'thankyou2010.com', 'thisisnotmyrealemail.com', 'throwawayemailaddress.com',
  'tittbit.in', 'tradermail.info', 'trash-mail.at', 'trash-mail.com',
  'trash-me.com', 'trash2009.com', 'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashmail.at', 'trashmail.me', 'trashmail.org',
  'trashmailer.com', 'trashymail.com', 'trashymail.net', 'turual.com',
  'twinmail.de', 'tyldd.com', 'uggsrock.com', 'upliftnow.com',
  'uplipht.com', 'venompen.com', 'veryreallyme.com', 'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net', 'viewcastmedia.org',
  'vomoto.com', 'vpn.st', 'vsimcard.com', 'vubby.com',
  'wasteland.rfc822.org', 'webemail.me', 'weg-werf-email.de',
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfmail.org', 'wh4f.org', 'whatiaas.com', 'whatpaas.com',
  'whyspam.me', 'wikidocuslice.com', 'willhackforfood.biz',
  'willselfdestruct.com', 'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net', 'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xents.com', 'xjoi.com', 'xmaily.com',
  'xoxy.net', 'yep.it', 'yogamaven.com', 'yuurok.com',
  'zehnminutenmail.de', 'zippymail.info', 'zoaxe.com', 'zoemail.org',
  'guerrillamail.de', 'mailinator.us', 'mailinator.co.uk',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return true;
  return DISPOSABLE_DOMAINS.has(domain);
}
